/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/UI/Buttons/BaseButton.vue')['default']
    BaseForm: typeof import('./src/components/UI/Forms/BaseForm.vue')['default']
    BaseInput: typeof import('./src/components/UI/Inputs/BaseInput.vue')['default']
    BaseLayout: typeof import('./src/components/UI/Layout/BaseLayout.vue')['default']
    CenterLayout: typeof import('./src/components/UI/Layout/CenterLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
