/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/UI/Buttons/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/UI/Inputs/BaseCheckbox.vue')['default']
    BaseForm: typeof import('./components/UI/Forms/BaseForm.vue')['default']
    BaseInput: typeof import('./components/UI/Inputs/BaseInput.vue')['default']
    BaseLayout: typeof import('./components/UI/Layout/BaseLayout.vue')['default']
    CenterLayout: typeof import('./components/UI/Layout/CenterLayout.vue')['default']
    MaterialIcon: typeof import('./components/UI/Icons/MaterialIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
